# Generated by Django 4.2.7 on 2023-12-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_artist_birth_date_artist_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
