# Generated by Django 4.2.7 on 2023-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='song.playlist'),
        ),
    ]
